kind: Deployment
apiVersion: apps/v1
metadata:
  name: mysql
  namespace: expense
  # these labels are deploymentrelated labels
  labels:
    component: mysql
    project: expense
    tier: db
spec:
  replicas: 10
  selector: 
    matchLabels:
     component: mysql
     project: expense
     tier: db
  # pod definition
  template:
    metadata:
      labels:
       component: mysql
       project: expense
       tier: db
    spec:
      containers:
      - name: mysql
        image: joindevops/mysql:v1.0